[workspace]
members = [
    "grpc",
    "grpc-protobuf",
    "grpc-examples/greeter",
    "grpc-examples/route_guide",
    "grpc-compiler",
    "grpc-compiler/test-protoc-plugin",
    "long-tests/with-rust",
    "interop",
    "protoc-rust-grpc",
]
