[package]

name = "grpc-protobuf"
version = "0.7.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Protobuf marshaller for gRPC"
repository = "https://github.com/stepancheg/grpc-rust"
readme = "../README.md"
keywords = ["grpc"]
edition = "2018"

[dependencies]
protobuf        = { version = "2", features = ["with-bytes"] }
grpc            = { version = "0.7.0", path = "../grpc" }
bytes           = "0.4"

[lib]
doctest = false
